version: 2

models:
  - name: stg_local_bike_bronze__brands
    description: "This model contains a list of nine brands"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null
          
  - name: stg_local_bike_bronze__categories
    description: "This model contains a list of seven categories for bicycle"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category"
        tests:
            - unique
            - not_null
  - name: stg_local_bike_bronze__customers
    description: "This model contains all customers"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer"
        tests:
            - unique
            - not_null

  - name: stg_local_bike_bronze__order_items
    description: "This model contains all order_items"
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each customer"
        tests:
            - unique
            - not_null